---
# Stackmate project configuration
framework: nodejs
# The repository to deploy from
repository: git@github.com:stackmate-io/sample-app-expressjs.git
# The cloud provider to use
provider: aws
# The region to deploy to
region: eu-central-1
# The provider credentials to use
providers:
  aws:
    access_key: "{{ lookup('env', 'STACKMATE_ACCESS_KEY') }}"
    secret: "{{ lookup('env', 'STACKMATE_SECRET') }}"
  github:
    access_key: "{{ lookup('env', 'STACKMATE_GITHUB_ID') }}"
    secret: "{{ lookup('env', 'STACKMATE_GITHUB_SECRET') }}"
    token: "{{ lookup('env', 'STACKMATE_GITHUB_TOKEN') }}"

# environments
production:
  # branch to deploy
  branch: master
  # domain to use
  domain: nodejs.ezploy.eu

  # services to use
  services:
    - name: nodejsapp-production
      type: application
      size: t2.nano
      dependencies:
        - type: nginx
        - type: nodejs
        - type: pm2
      storage: 20
